Vagrant.configure("2") do |config|
  ### Jenkins ###
  config.vm.define "jenkins01" do |jenkins01|
    jenkins01.vm.box = "ubuntu/bionic64"
    jenkins01.vm.hostname = "jenkins01"
    jenkins01.vm.network "private_network", ip: "192.168.56.11"
    jenkins01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    jenkins01.vm.provision "shell", path: "bash1-jenkins-setup.sh"
  end

  ### Nexus ###
  config.vm.define "nexus01" do |nexus01|
    nexus01.vm.box = "geerlingguy/centos7"
    nexus01.vm.hostname = "nexus01"
    nexus01.vm.network "private_network", ip: "192.168.56.12"
    nexus01.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 2
    end
    nexus01.vm.provision "shell", path: "bash2-nexus-setup.sh"
  end

  ### Sonarqube ###
  config.vm.define "sonar01" do |sonar01|
    sonar01.vm.box = "geerlingguy/centos7"
    sonar01.vm.hostname = "sonar01"
    sonar01.vm.network "private_network", ip: "192.168.56.12"
    sonar01.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 2
    end
    sonar01.vm.provision "shell", path: "bash3-jenkins-setup.sh"
  end
end
