Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"

  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/bionic64"

    web01.vm.network "private_network", ip: "192.168.56.11"

    web01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end

    web01.vm.provision "shell", inline: <<-SHELL
      sudo apt update
      sudo apt install -y apache2 unzip wget

      sudo systemctl start apache2
      sudo systemctl enable apache2

      cd /tmp/
      sudo wget https://www.tooplate.com/zip-templates/2121_wave_cafe.zip
      sudo unzip -o 2121_wave_cafe.zip
      cd 2121_wave_cafe
      sudo cp -r * /var/www/html

      sudo systemctl restart apache2
    SHELL
  end

  config.vm.define "db01" do |db01|
    db01.vm.box = "geerlingguy/centos7"

    db01.vm.network "private_network", ip: "192.168.56.12"

    db01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end

    db01.vm.provision "shell", inline: <<-SHELL
      sudo yum install -y mariadb-server

      sudo systemctl enable mariadb
      sudo systemctl start mariadb

      sudo mysql -u root -e "CREATE DATABASE wordpress;"
      sudo mysql -u root -e "CREATE USER wordpress@localhost IDENTIFIED BY 'Vagrant@123';"
      sudo mysql -u root -e "GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON wordpress.* TO wordpress@localhost;"
      sudo mysql -u root -e "FLUSH PRIVILEGES;"

      sudo systemctl restart mariadb

      sudo reboot
    SHELL
  end
end

